"""perfil laboral del doctor (hora_entrada, dias_laborales)

Revision ID: 1d7cdc6fd04a
Revises: b294abd63484
Create Date: 2026-06-17 21:20:44.163767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7cdc6fd04a'
down_revision: Union[str, None] = 'b294abd63484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hora_entrada', sa.String(length=5), nullable=True))
    op.add_column('usuarios', sa.Column('dias_laborales', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'dias_laborales')
    op.drop_column('usuarios', 'hora_entrada')
    # ### end Alembic commands ###
