"""descuento porcentual en ventas

Revision ID: 1e69a55749e1
Revises: f77918a9e992
Create Date: 2026-06-25 08:49:11.875552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e69a55749e1'
down_revision: Union[str, None] = 'f77918a9e992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'foto_url')
    op.add_column('ventas', sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'descuento_pct')
    op.add_column('pacientes', sa.Column('foto_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
