"""servicios y ventas mixtas producto servicio

Revision ID: 4092ce82ade3
Revises: b26a50a46993
Create Date: 2026-06-12 15:29:44.474759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4092ce82ade3'
down_revision: Union[str, None] = 'b26a50a46993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_variable', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venta_items', sa.Column('servicio_id', sa.Integer(), nullable=True))
    op.add_column('venta_items', sa.Column('descripcion', sa.String(length=200), nullable=True))
    op.alter_column('venta_items', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(
        'venta_items_servicio_id_fkey', 'venta_items', 'servicios', ['servicio_id'], ['id']
    )

    # Backfill: snapshot del nombre del producto en los items existentes
    op.execute("""
        UPDATE venta_items vi
        SET descripcion = p.nombre
        FROM productos p
        WHERE vi.producto_id = p.id AND vi.descripcion IS NULL
    """)

    # Seed: servicios por defecto de la veterinaria
    op.execute("""
        INSERT INTO servicios (nombre, descripcion, precio, precio_variable, activo, creado_en)
        VALUES
          ('Consulta general', 'Atención clínica general',         50.00, false, true, now()),
          ('Baño',             'Baño e higiene',                   40.00, false, true, now()),
          ('Corte de pelo',    'Corte y arreglo estético',         35.00, false, true, now()),
          ('Operación',        'Intervención quirúrgica (monto según procedimiento)', NULL, true, true, now())
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venta_items_servicio_id_fkey', 'venta_items', type_='foreignkey')
    op.alter_column('venta_items', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('venta_items', 'descripcion')
    op.drop_column('venta_items', 'servicio_id')
    op.drop_table('servicios')
    # ### end Alembic commands ###
