"""documentos complementarios del paciente

Revision ID: 73a02d5817d8
Revises: 1e69a55749e1
Create Date: 2026-06-26 00:54:28.838673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a02d5817d8'
down_revision: Union[str, None] = '1e69a55749e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.LargeBinary(), nullable=False),
    sa.Column('subido_por', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_paciente')
    # ### end Alembic commands ###
