"""bitacora de actividad

Revision ID: 85bca099fe55
Revises: 1d7cdc6fd04a
Create Date: 2026-06-18 00:10:14.845545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bca099fe55'
down_revision: Union[str, None] = '1d7cdc6fd04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('accion', sa.String(length=150), nullable=True),
    sa.Column('metodo', sa.String(length=10), nullable=True),
    sa.Column('ruta', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades')
    # ### end Alembic commands ###
