"""detalle en bitacora

Revision ID: 8e7b47d023fa
Revises: 85bca099fe55
Create Date: 2026-06-18 00:28:39.669443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7b47d023fa'
down_revision: Union[str, None] = '85bca099fe55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('detalle', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actividades', 'detalle')
    # ### end Alembic commands ###
