"""agregar evaluadores y encuestas sus tam

Revision ID: 9bf6957b70e0
Revises: d6bea0e3db5d
Create Date: 2026-06-10 16:45:27.326151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf6957b70e0'
down_revision: Union[str, None] = 'd6bea0e3db5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_sus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=False),
    sa.Column('p1', sa.Integer(), nullable=False),
    sa.Column('p2', sa.Integer(), nullable=False),
    sa.Column('p3', sa.Integer(), nullable=False),
    sa.Column('p4', sa.Integer(), nullable=False),
    sa.Column('p5', sa.Integer(), nullable=False),
    sa.Column('p6', sa.Integer(), nullable=False),
    sa.Column('p7', sa.Integer(), nullable=False),
    sa.Column('p8', sa.Integer(), nullable=False),
    sa.Column('p9', sa.Integer(), nullable=False),
    sa.Column('p10', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['evaluadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_tam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=False),
    sa.Column('p1', sa.Integer(), nullable=False),
    sa.Column('p2', sa.Integer(), nullable=False),
    sa.Column('p3', sa.Integer(), nullable=False),
    sa.Column('p4', sa.Integer(), nullable=False),
    sa.Column('p5', sa.Integer(), nullable=False),
    sa.Column('p6', sa.Integer(), nullable=False),
    sa.Column('p7', sa.Integer(), nullable=False),
    sa.Column('p8', sa.Integer(), nullable=False),
    sa.Column('p9', sa.Integer(), nullable=False),
    sa.Column('p10', sa.Integer(), nullable=False),
    sa.Column('p11', sa.Integer(), nullable=False),
    sa.Column('p12', sa.Integer(), nullable=False),
    sa.Column('util_percibida', sa.Float(), nullable=True),
    sa.Column('facilidad_uso', sa.Float(), nullable=True),
    sa.Column('intencion_uso', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['evaluadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_tam')
    op.drop_table('respuestas_sus')
    op.drop_table('evaluadores')
    # ### end Alembic commands ###
