"""metricas tiempo registro historia

Revision ID: 9c714e0c6e92
Revises: e311a89ac3ea
Create Date: 2026-06-13 02:12:19.463109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c714e0c6e92'
down_revision: Union[str, None] = 'e311a89ac3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historias_clinicas', sa.Column('segundos_registro', sa.Integer(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('metodo_registro', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historias_clinicas', 'metodo_registro')
    op.drop_column('historias_clinicas', 'segundos_registro')
    # ### end Alembic commands ###
