"""ampliar productos codigo proveedor unidad descripcion

Revision ID: b26a50a46993
Revises: 348989a7fe2f
Create Date: 2026-06-12 15:14:53.694070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26a50a46993'
down_revision: Union[str, None] = '348989a7fe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('codigo', sa.String(length=20), nullable=True))
    op.add_column('productos', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('productos', sa.Column('proveedor', sa.String(length=150), nullable=True))
    op.add_column('productos', sa.Column('unidad', sa.String(length=30), nullable=True))

    # Backfill: asignar código correlativo por categoría a los productos existentes
    conn = op.get_bind()
    prefijos = {"comida": "COM", "accesorio": "ACC", "medicamento": "MED"}
    contadores: dict[str, int] = {}
    filas = conn.execute(
        sa.text("SELECT id, categoria FROM productos ORDER BY id")
    ).fetchall()
    for pid, categoria in filas:
        prefijo = prefijos.get(categoria or "", "GEN")
        contadores[prefijo] = contadores.get(prefijo, 0) + 1
        codigo = f"{prefijo}-{contadores[prefijo]:04d}"
        conn.execute(
            sa.text("UPDATE productos SET codigo = :codigo WHERE id = :id"),
            {"codigo": codigo, "id": pid},
        )

    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_column('productos', 'unidad')
    op.drop_column('productos', 'proveedor')
    op.drop_column('productos', 'descripcion')
    op.drop_column('productos', 'codigo')
    # ### end Alembic commands ###
