"""asistencias y autoria de historias/citas

Revision ID: b294abd63484
Revises: ddbf722692ac
Create Date: 2026-06-17 18:22:05.811839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b294abd63484'
down_revision: Union[str, None] = 'ddbf722692ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_ingreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.Column('registrado_por', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('citas', sa.Column('veterinario_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_citas_veterinario', 'citas', 'usuarios', ['veterinario_id'], ['id'])
    op.add_column('historias_clinicas', sa.Column('veterinario_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_historias_veterinario', 'historias_clinicas', 'usuarios', ['veterinario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_historias_veterinario', 'historias_clinicas', type_='foreignkey')
    op.drop_column('historias_clinicas', 'veterinario_id')
    op.drop_constraint('fk_citas_veterinario', 'citas', type_='foreignkey')
    op.drop_column('citas', 'veterinario_id')
    op.drop_table('asistencias')
    # ### end Alembic commands ###
