"""esquema inicial postgres

Revision ID: bf4bf6080d9b
Revises: 
Create Date: 2026-06-10 14:59:37.262470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4bf6080d9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_dni'), 'clientes', ['dni'], unique=True)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historias_clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anamnesis', sa.Text(), nullable=True),
    sa.Column('examen_fisico', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historias_clinicas')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_clientes_dni'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
