"""sincronizar columnas faltantes

Revision ID: ddbf722692ac
Revises: 9c714e0c6e92
Create Date: 2026-06-16 02:55:51.199530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbf722692ac'
down_revision: Union[str, None] = '9c714e0c6e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('foto_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'foto_url')
    # ### end Alembic commands ###
