"""usuarios roles, ficha mascota ampliada, metodo_pago, kardex

Revision ID: e311a89ac3ea
Revises: 4092ce82ade3
Create Date: 2026-06-12 21:13:59.587761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e311a89ac3ea'
down_revision: Union[str, None] = '4092ce82ade3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_resultante', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=60), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pacientes', sa.Column('sexo', sa.String(length=10), nullable=True))
    op.add_column('pacientes', sa.Column('esterilizado', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    op.add_column('pacientes', sa.Column('microchip', sa.String(length=50), nullable=True))
    op.add_column('pacientes', sa.Column('color', sa.String(length=60), nullable=True))
    op.add_column('pacientes', sa.Column('alergias', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('condiciones_cronicas', sa.Text(), nullable=True))
    op.add_column('ventas', sa.Column('metodo_pago', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'metodo_pago')
    op.drop_column('pacientes', 'condiciones_cronicas')
    op.drop_column('pacientes', 'alergias')
    op.drop_column('pacientes', 'color')
    op.drop_column('pacientes', 'microchip')
    op.drop_column('pacientes', 'fecha_nacimiento')
    op.drop_column('pacientes', 'esterilizado')
    op.drop_column('pacientes', 'sexo')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
